baseURL = 'https://seasons.ally.id/'
languageCode = 'en-us'
title = 'Seasons'
theme = 'maddybook'

[permalinks]
    post = '/:filename/'

[params]
    author = 'Madison Scott-Clary'
    home = 'https://makyo.ink'
    copyright = 2022
    customCSS = ['https://fontlibrary.org/face/coelacanth', '/seasons.css']

[markup.goldmark.renderer]
    unsafe = true

